version: "3.8"

services:
  mywebapp:
    build: .
    container_name: "myreactapp_${BRANCH_NAME}"
    ports:
      - "${PORT}:${PORT}"
    command: npm run dev -- --host 0.0.0.0 --port ${PORT}
    environment:
      - NODE_ENV=${BRANCH_NAME}
      - PORT=${PORT}

